version: "3"
services:
  api:
    container_name: dev_todo_api
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - PRODUCTION_ENVIRONMENT=${PRODUCTION_ENVIRONMENT}
    volumes:
      - ./:/usr/src/app
